#!/usr/bin/env python3
"""
scaffold.py — lay out a new learning project.

    scaffold.py <project-root> "<Subject>" [--corpus] [--lang ru]

What it does NOT do: write the domain layer. `.tutor/config.yaml` is written by
/learning-init from the interview, because it is the user's judgement about
their own field and no script can guess it.

What it does do, and why it matters: the generated Makefile points at the
plugin's runtime instead of copying it. That single line is what keeps the core
updatable — improve the method in the plugin and every existing project gets it,
instead of five projects sitting on five frozen forks of the method.
"""
from __future__ import annotations

import argparse
import os
import re
from datetime import date
from pathlib import Path

RUNTIME = Path(__file__).resolve().parent.parent

DIRS_BASE = [
    "wiki/concepts", "wiki/tracks", "wiki/entities", "wiki/summaries",
    "raw/articles", "raw/notes", "raw/refs",
    "outputs/queries", "outputs/solutions",
    "checks", "audit/resolved", "log", "templates", ".tutor",
]
DIRS_CORPUS = ["raw/books"]

SHIM = """\
#!/usr/bin/env python3
\"\"\"Entry point for this base.

    python tutor.py setup      # build the environment
    python tutor.py check      # recompute the confidence tags
    python tutor.py help

A pointer, not a copy: every line of logic lives in the plugin runtime, so
improving the method reaches this project without touching this file.
\"\"\"
import os
import runpy
import sys
from pathlib import Path

RUNTIME = Path(r"{runtime}")
os.environ.setdefault("TUTOR_PROJECT_ROOT", str(Path(__file__).resolve().parent))
sys.argv[0] = str(RUNTIME / "scripts" / "tutor.py")
runpy.run_path(str(RUNTIME / "scripts" / "tutor.py"), run_name="__main__")
"""

MAKEFILE = """\
# Generated by tutor-skills. Sugar over `python3 tutor.py <command>`: the logic
# lives in the plugin runtime and works the same on Windows, where make does not
# exist. Anything you can do here you can do with tutor.py directly.
PY ?= python3

.DEFAULT_GOAL := help

help setup check check-dry lint reflow reflow-check audit{corpus_goals}:
\t@$(PY) tutor.py $@

# The only target with arguments:
#   make audit-new P="page" T="exact quote" [S=warn K=kind C="what is wrong"]
audit-new:
\t@$(PY) tutor.py audit-new "$(P)" $(if $(T),--text "$(T)") \\
\t  $(if $(L),--line $(L)) $(if $(S),--severity $(S)) $(if $(K),--kind $(K)) \\
\t  $(if $(C),--comment "$(C)")

.PHONY: help setup check check-dry lint reflow reflow-check audit audit-new{corpus_goals}
"""

CORPUS_GOALS = " find ocr ocr-status catalog"

PYPROJECT = """\
[project]
name = "{slug}"
version = "0.1.0"
description = "Learning base: {title}"
requires-python = ">=3.10"
# The core runs from the plugin, not from here. This file exists only so that
# `make setup` can build a venv with the one dependency the core needs.
dependencies = ["pyyaml>=6"]
"""

GITIGNORE_BASE = """\
.venv/
__pycache__/
*.pyc
.obsidian/workspace.json
"""

GITIGNORE_CORPUS = """
# Sources are large binaries: they live locally, their catalogue is versioned.
raw/books/*.pdf
raw/books/*.djvu

# The text index is fully derived from the PDFs and rebuilt by `make ocr`.
raw/books/.ocr/*.txt
raw/books/.ocr/*.png

# But the printed-page offsets are small, precious, and hand-verified.
!raw/books/.ocr/*.meta.json
"""

CLAUDE_MD = """\
# {title}

> Schema of this base. Read at the start of **every** session together with `wiki/index.md`. The machine-readable half lives in `.tutor/config.yaml`; this file is the prose half.

## 0. Commands on this machine

{commands}

`tutor.py` is a pointer at the plugin runtime, not a copy of it: improving the method updates this project without touching the file. `tutor.py help` lists everything.

## 1. Who is learning and why

<!-- Filled in by /learning-init from the phase 1 interview. -->

## 2. What we are building

| Layer | What it is |
|---|---|
| `wiki/concepts/` | Atomic concepts, all depth levels inside one page |
| `wiki/tracks/` | Route pages: the order of concepts and **why** that order |

## 3. Depth levels

<!-- Filled in by /learning-init: which levels this subject supports, and what each one means here. A level may be declared inapplicable with a reason; it may not be silently skipped. -->

## 4. Trustworthiness

The `confidence` tag is written **only** by `make check`. Never by hand. Thresholds, what counts as a source, and what independence means in this subject are in `.tutor/config.yaml`.

## 5. Canon

<!-- Filled in by /learning-init: arbiters by area, problem sets, what wins on a contradiction. -->

## 6. Problems

<!-- Filled in by /learning-init: how many per concept, their roles, where they come from, and what happens when the sources contain none. -->

## 7. Conventions

- **Line breaks in source: none.** One paragraph = one line, however long. Obsidian's Live Preview is an editor: a wrap in the source shows up as a real break mid-sentence. Check and fix with `make reflow-check` / `make reflow`.
- **Diagrams:** mermaid only, never ASCII art.
- **Page length:** 400–1200 words of connected prose; collapsed hint blocks do not count. Past that, split into a subfolder with an `index.md`.

## 8. Deliberately out of scope

<!-- Filled in by /learning-init at phase 2: things considered and turned down, one line of reasoning each. Not a wishlist — a record of decisions, so the same idea is not re-argued from nothing every few months. -->

## 9. Current state

Scaffolded {today}. Domain layer at phase 1 — every page is capped at `draft` until /learning-init closes phase 2.
"""

INDEX_MD = """\
# Index — {title}

> One sentence of scope goes here.

## Tracks

## Concepts

## Entities

## Summaries

## Open questions
"""


def write(root: Path, rel: str, text: str, force: bool = False) -> None:
    path = root / rel
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and not force:
        print(f"· kept   {rel}")
        return
    path.write_text(text, encoding="utf-8")
    print(f"✎ wrote  {rel}")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("root")
    ap.add_argument("title")
    ap.add_argument("--corpus", action="store_true",
                    help="the subject is learned from a corpus of books (physics, "
                         "chemistry, history, mathematics) rather than from live docs")
    ap.add_argument("--runtime", default=str(RUNTIME),
                    help="path to the plugin runtime the project will point at")
    a = ap.parse_args()

    root = Path(a.root).resolve()
    for d in DIRS_BASE + (DIRS_CORPUS if a.corpus else []):
        (root / d).mkdir(parents=True, exist_ok=True)
    for keep in ["audit/.gitkeep", "audit/resolved/.gitkeep", "checks/.gitkeep"]:
        (root / keep).touch()

    write(root, "tutor.py", SHIM.format(runtime=a.runtime))
    if os.name != "nt":
        # No Makefile on Windows: there is no make, and tutor.py is the interface
        # everywhere anyway. On Unix it stays as a convenience.
        write(root, "Makefile",
              MAKEFILE.format(corpus_goals=CORPUS_GOALS if a.corpus else ""))
    write(root, ".gitignore",
          GITIGNORE_BASE + (GITIGNORE_CORPUS if a.corpus else ""))
    slug = re.sub(r"[^a-z0-9]+", "-", a.title.lower()).strip("-") or "learning-base"
    write(root, "pyproject.toml", PYPROJECT.format(slug=slug, title=a.title))
    if os.name == "nt":
        commands = ("Windows: there is no `make` here, so **every command in this file and in "
                    "the skills is run as `python tutor.py <command>`** — `python tutor.py check`, "
                    "`python tutor.py lint`, `python tutor.py audit`. Where any document says "
                    "`make X`, read it as `python tutor.py X`.")
    else:
        commands = ("`make check`, `make lint`, `make audit` — and the identical, "
                    "platform-neutral form `python3 tutor.py check` if make is ever missing. "
                    "The Makefile is sugar over `tutor.py`; both run the same code.")
    write(root, "CLAUDE.md",
          CLAUDE_MD.format(title=a.title, today=date.today(), commands=commands))
    write(root, "wiki/index.md", INDEX_MD.format(title=a.title))
    write(root, f"log/{date.today():%Y%m%d}.md",
          f"# {date.today()}\n\n## [--:--] scaffold | {a.title}\n")

    for tpl in sorted((RUNTIME / "templates").glob("*.md")):
        write(root, f"templates/{tpl.name}", tpl.read_text(encoding="utf-8"))

    print(f"\nScaffolded {root}")
    setup_cmd = "python tutor.py setup" if os.name == "nt" else "make setup"
    check_cmd = "python tutor.py check" if os.name == "nt" else "make check"
    print(f"Next: `{setup_cmd}`, then /learning-init writes .tutor/config.yaml — the domain layer.")
    print(f"Without it `{check_cmd}` will refuse to run, and that is on purpose:")
    print("the core does not guess what a source or a check means in your field.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
