#!/usr/bin/env python3
"""
scaffold.py — lay out a new learning project.

    scaffold.py <project-root> "<Subject>" [--corpus] [--lang ru]

What it does NOT do: write the domain layer. `.tutor/config.yaml` is written by
/learning-init from the interview, because it is the user's judgement about
their own field and no script can guess it.

What it does do, and why it matters: the generated Makefile points at the
plugin's runtime instead of copying it. That single line is what keeps the core
updatable — improve the method in the plugin and every existing project gets it,
instead of five projects sitting on five frozen forks of the method.
"""
from __future__ import annotations

import argparse
import re
from datetime import date
from pathlib import Path

RUNTIME = Path(__file__).resolve().parent.parent

DIRS_BASE = [
    "wiki/concepts", "wiki/tracks", "wiki/entities", "wiki/summaries",
    "raw/articles", "raw/notes", "raw/refs",
    "outputs/queries", "outputs/solutions",
    "checks", "audit/resolved", "log", "templates", ".tutor",
]
DIRS_CORPUS = ["raw/books"]

MAKEFILE = """\
# Generated by tutor-skills. The runtime lives in the plugin, not here —
# that is deliberate: update the plugin and this project gets the new core.
TUTOR := {runtime}
# Prefer the project venv when it exists; `make setup` creates it.
PY    := $(shell test -x .venv/bin/python && echo .venv/bin/python || echo python3)

export TUTOR_PROJECT_ROOT := $(CURDIR)

.DEFAULT_GOAL := help

setup:           ## create .venv and install the one dependency (PyYAML)
	@command -v uv >/dev/null 2>&1 \
	  && uv venv --quiet && uv pip install --quiet pyyaml \
	  || (python3 -m venv .venv && .venv/bin/pip install --quiet pyyaml)
	@echo "✓ .venv ready. Now: make check"

help:            ## show this list
\t@grep -hE '^[a-zA-Z_-]+:.*?## ' $(MAKEFILE_LIST) \\
\t  | awk -F':.*?## ' '{{printf "  \\033[36m%-13s\\033[0m %s\\n", $$1, $$2}}'

check:           ## check pages and recompute `confidence` (the ONLY way the tag changes)
\t$(PY) $(TUTOR)/scripts/check_pages.py

check-dry:       ## same, but write nothing
\t$(PY) $(TUTOR)/scripts/check_pages.py --dry-run

lint:            ## health-check of the wiki graph
\t@$(PY) $(TUTOR)/scripts/lint_wiki.py .

reflow:          ## one paragraph = one line (Obsidian Live Preview)
\t$(PY) $(TUTOR)/scripts/reflow_md.py

reflow-check:    ## show where paragraphs are still hard-wrapped
\t$(PY) $(TUTOR)/scripts/reflow_md.py --check

audit-new:       ## file a note: make audit-new P="page" T="quote" [S=warn K=kind C="text"]
\t@$(PY) $(TUTOR)/scripts/new_audit.py "$(P)" $(if $(T),--text "$(T)") \\
\t  $(if $(L),--line $(L)) $(if $(S),--severity $(S)) $(if $(K),--kind $(K)) \\
\t  $(if $(C),--comment "$(C)")

audit:           ## open notes from audit/, by severity
\t$(PY) $(TUTOR)/scripts/audit_review.py . --open
{corpus_targets}
.PHONY: setup help check check-dry lint reflow reflow-check audit audit-new{corpus_phony}
"""

CORPUS_TARGETS = """
find:            ## search the corpus: make find Q="query" [B=Author]
\t@$(PY) $(TUTOR)/capabilities/corpus/find_in_book.py "$(Q)" \\
\t  $(if $(B),--book "$(B)",--canon)

ocr:             ## extend the text index of the corpus (resumable)
\t$(PY) $(TUTOR)/capabilities/corpus/ocr_book.py --all --dpi 300

ocr-status:      ## what is already indexed
\t$(PY) $(TUTOR)/capabilities/corpus/ocr_book.py --status

catalog:         ## rebuild raw/books/index.md
\t$(PY) $(TUTOR)/capabilities/corpus/catalog.py
"""

PYPROJECT = """\
[project]
name = "{slug}"
version = "0.1.0"
description = "Learning base: {title}"
requires-python = ">=3.10"
# The core runs from the plugin, not from here. This file exists only so that
# `make setup` can build a venv with the one dependency the core needs.
dependencies = ["pyyaml>=6"]
"""

GITIGNORE_BASE = """\
.venv/
__pycache__/
*.pyc
.obsidian/workspace.json
"""

GITIGNORE_CORPUS = """
# Sources are large binaries: they live locally, their catalogue is versioned.
raw/books/*.pdf
raw/books/*.djvu

# The text index is fully derived from the PDFs and rebuilt by `make ocr`.
raw/books/.ocr/*.txt
raw/books/.ocr/*.png

# But the printed-page offsets are small, precious, and hand-verified.
!raw/books/.ocr/*.meta.json
"""

CLAUDE_MD = """\
# {title}

> Schema of this base. Read at the start of **every** session together with `wiki/index.md`. The machine-readable half lives in `.tutor/config.yaml`; this file is the prose half.

## 1. Who is learning and why

<!-- Filled in by /learning-init from the phase 1 interview. -->

## 2. What we are building

| Layer | What it is |
|---|---|
| `wiki/concepts/` | Atomic concepts, all depth levels inside one page |
| `wiki/tracks/` | Route pages: the order of concepts and **why** that order |

## 3. Depth levels

<!-- Filled in by /learning-init: which levels this subject supports, and what each one means here. A level may be declared inapplicable with a reason; it may not be silently skipped. -->

## 4. Trustworthiness

The `confidence` tag is written **only** by `make check`. Never by hand. Thresholds, what counts as a source, and what independence means in this subject are in `.tutor/config.yaml`.

## 5. Canon

<!-- Filled in by /learning-init: arbiters by area, problem sets, what wins on a contradiction. -->

## 6. Problems

<!-- Filled in by /learning-init: how many per concept, their roles, where they come from, and what happens when the sources contain none. -->

## 7. Conventions

- **Line breaks in source: none.** One paragraph = one line, however long. Obsidian's Live Preview is an editor: a wrap in the source shows up as a real break mid-sentence. Check and fix with `make reflow-check` / `make reflow`.
- **Diagrams:** mermaid only, never ASCII art.
- **Page length:** 400–1200 words of connected prose; collapsed hint blocks do not count. Past that, split into a subfolder with an `index.md`.

## 8. Current state

Scaffolded {today}. Domain layer at phase 1 — every page is capped at `draft` until /learning-init closes phase 2.
"""

INDEX_MD = """\
# Index — {title}

> One sentence of scope goes here.

## Tracks

## Concepts

## Entities

## Summaries

## Open questions
"""


def write(root: Path, rel: str, text: str, force: bool = False) -> None:
    path = root / rel
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and not force:
        print(f"· kept   {rel}")
        return
    path.write_text(text, encoding="utf-8")
    print(f"✎ wrote  {rel}")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("root")
    ap.add_argument("title")
    ap.add_argument("--corpus", action="store_true",
                    help="the subject is learned from a corpus of books (physics, "
                         "chemistry, history, mathematics) rather than from live docs")
    ap.add_argument("--runtime", default=str(RUNTIME),
                    help="path to the plugin runtime the project will point at")
    a = ap.parse_args()

    root = Path(a.root).resolve()
    for d in DIRS_BASE + (DIRS_CORPUS if a.corpus else []):
        (root / d).mkdir(parents=True, exist_ok=True)
    for keep in ["audit/.gitkeep", "audit/resolved/.gitkeep", "checks/.gitkeep"]:
        (root / keep).touch()

    write(root, "Makefile", MAKEFILE.format(
        runtime=a.runtime,
        corpus_targets=CORPUS_TARGETS if a.corpus else "",
        corpus_phony=" find ocr ocr-status catalog" if a.corpus else ""))
    write(root, ".gitignore",
          GITIGNORE_BASE + (GITIGNORE_CORPUS if a.corpus else ""))
    slug = re.sub(r"[^a-z0-9]+", "-", a.title.lower()).strip("-") or "learning-base"
    write(root, "pyproject.toml", PYPROJECT.format(slug=slug, title=a.title))
    write(root, "CLAUDE.md", CLAUDE_MD.format(title=a.title, today=date.today()))
    write(root, "wiki/index.md", INDEX_MD.format(title=a.title))
    write(root, f"log/{date.today():%Y%m%d}.md",
          f"# {date.today()}\n\n## [--:--] scaffold | {a.title}\n")

    for tpl in sorted((RUNTIME / "templates").glob("*.md")):
        write(root, f"templates/{tpl.name}", tpl.read_text(encoding="utf-8"))

    print(f"\nScaffolded {root}")
    print("Next: `make setup`, then /learning-init writes .tutor/config.yaml — the domain layer.")
    print("Without it `make check` will refuse to run, and that is on purpose:")
    print("the core does not guess what a source or a check means in your field.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
